name: Validate JSONs

on: [push]

jobs:
  copy-configuration-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Different Node versions possible. Each node version will trigger the action
        node-version:
          - 22.x
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          # The source folder contains the configuration files
          path: source
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          path: target
      # Extra step to debug the file structure
      - name: List file structure of source dir
        shell: bash
        run: |
          ls source
      - name: List file structure of target dir
        shell: bash
        run: |
          ls target
      - name: Validate JSON
        id: validate
        # https://github.com/marketplace/actions/json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.5.0
        with:
          json_schema: source/schemas/configuration.json
          json_extension: json
          base_dir: target
          comment: true
          use_gitignore: false
          json_exclude_regex: 'configuration\.json$'
      - name: Log validation result to summary
        run: |
          echo "# Summary" >> $GITHUB_STEP_SUMMARY
          if [ ${{ steps.validate.outputs.success }} == "true" ]; then
            echo "All configuration file(s) in the repository are valid!" >> $GITHUB_STEP_SUMMARY
          else
            echo "There are some errors in the configuration file(s). Please check the logs to see which files" >> $GITHUB_STEP_SUMMARY
          fi
